baseURL: "https://corymccartan.github.io/"
languageCode: "en-us"
title: "Cory McCartan"
permalinks:
    posts: /:year/:month/:slug/
    projects: /projects/:slug/
markup:
  goldmark:
    renderer:
      unsafe: true
